#!/bin/bash

# Backup using rsync created 02/07/2023
# modified to use --exclude-from=backup.exclude 02/09/2023

# remove old tmp/rlog file
rm /home/bob/tmp/rlog

rsync -a --log-file=/home/bob/tmp/rlog --exclude-from=/usr/local/bin/backup-exclude /home/bob/ /backup/home$(date +%Y_%m_%d)

# remove backup files older than 10 days
rm -rf /backup/home$(date --date="10 days ago" +"%Y_%m_%d")
